### PR TITLE
Integrate AXI RT feature

### PR DESCRIPTION
**Pull request by alex96295**

### CODE REVIEW

**Comment by alex96295** [comment]
@yvantor here as you see we are temporarily pointing to a commit of `axi` that I added in the `Bender.local`. It should soon become a release, but at the moment another bug has to addressed and fixed beforehand

**Comment by yvantor** [comment]
> @yvantor here as you see we are temporarily pointing to a commit of `axi` that I added in the `Bender.local`. The commits build on top of `axi-v0.38.0-beta.8`. It should soon become a release, but at the moment another bug has to be addressed and fixed beforehand.
> 
> I think we should merge this when the CI passes and then update AXI to the nearest release as soon as there is one.

Did you mean `axi-v0.39.0-beta.8`?

**Comment by yvantor** [comment]
> > @yvantor here as you see we are temporarily pointing to a commit of `axi` that I added in the `Bender.local`. The commits build on top of `axi-v0.38.0-beta.8`. It should soon become a release, but at the moment another bug has to be addressed and fixed beforehand.
> > I think we should merge this when the CI passes and then update AXI to the nearest release as soon as there is one.
> 
> Did you mean `axi-v0.39.0-beta.8`?

If it is not based on v0.39 I suggest to at least rebase it so that we do not downgrade the version too much.

**Comment by alex96295** [comment]
> > @yvantor here as you see we are temporarily pointing to a commit of `axi` that I added in the `Bender.local`. The commits build on top of `axi-v0.38.0-beta.8`. It should soon become a release, but at the moment another bug has to be addressed and fixed beforehand.
> > I think we should merge this when the CI passes and then update AXI to the nearest release as soon as there is one.
> 
> Did you mean `axi-v0.39.0-beta.8`?

Yes sure

**Comment by alex96295** [comment]
> > > @yvantor here as you see we are temporarily pointing to a commit of `axi` that I added in the `Bender.local`. The commits build on top of `axi-v0.38.0-beta.8`. It should soon become a release, but at the moment another bug has to be addressed and fixed beforehand.
> > > I think we should merge this when the CI passes and then update AXI to the nearest release as soon as there is one.
> > 
> > 
> > Did you mean `axi-v0.39.0-beta.8`?
> 
> If it is not based on v0.39 I suggest to at least rebase it so that we do not downgrade the version too much.

My bad, I meant v0.39-beta.8 :)

**Review by yvantor — APPROVED** [review]
I think having temporarily a commit for the AXI is not too much of a big issue as long as we can make sure we come back to pointing to a release soon. By the way, if it is not too urgent to merge it now, I would suggest to keep this open until there is an official release with the RT changes in it. If there is a real urgency for merging this, then proceed.

**Pull request merged**
