### PR TITLE
Fix and improve `hyperbus_wrap`

### PR DESCRIPTION
**Pull request by luca-valente**
- [x] Unroll input/output structs and include pads
- [x] Fix instantiation parameters.

### CODE REVIEW

**Comment by anga93** [comment]
Hi Luca, why are you adding the pads here? The pads are instantiated in the non-free repo, also for the hyper

**Comment by luca-valente** [comment]
@anga93 I just need a wrapper for the time being, then we can move them wherever.

**Comment by anga93** [comment]
ok got it

**Comment by alex96295** [comment]
Rebased onto main

**Comment by alex96295** [comment]
Merging when the CI passes

**Review by alex96295 — APPROVED** [review]

**Comment by alex96295** [comment]
lgtm

**Pull request merged**
