### PR TITLE
ci: Run litmus tests on scheduled pipelines

### PR DESCRIPTION
**Pull request by niwis**
- Pass pipeline source to child
- Bump carfield-nonfree

### CODE REVIEW

**Review by alex96295 — APPROVED** [review]
LGTM on my side, is the CI failing just for the expired polling time?

**Comment by niwis** [comment]
Seems to be a gitlab bug. I'm looking into it

**Comment by alex96295** [comment]
Is it fixed now?

**Comment by niwis** [comment]
Yep ready to merge from my side

**Comment by alex96295** [comment]
> Yep ready to merge from my side

Alright, thanks for this

**Pull request merged**
