### PR TITLE
Update security island reset interface

### PR DESCRIPTION
**Pull request by alex96295**
In security island:

- [x] Add axi isolate 
- [x] Add power-on reset

### CODE REVIEW

**Review by yvantor — APPROVED** [review]
Looks good! We can merge as soon as the CI concludes.

**Comment by alex96295** [comment]
> Looks good! We can merge as soon as the CI concludes.

It is not ready yet. The `isolate` is missing in this island, and needs to be added

**Comment by yvantor** [comment]
> > Looks good! We can merge as soon as the CI concludes.
> 
> It is not ready yet. The `isolate` is missing in this island, and needs to be added

I was convinced it was already added much prior than this PR so I did not check for the isolate.

**Comment by alex96295** [comment]
> > > Looks good! We can merge as soon as the CI concludes.
> > 
> > 
> > It is not ready yet. The `isolate` is missing in this island, and needs to be added
> 
> I was convinced it was already added much prior than this PR so I did not check for the isolate.

No problem, I also noticed only now

**Pull request merged**
