### PR TITLE
Fix FPGA implementation

### PR DESCRIPTION
**Pull request by yvantor**
Bump cluster commit to fix CSR assignment that breaks FPGA imlementation.

### CODE REVIEW

**Review by alex96295 — APPROVED** [review]
Did you try locally? I am anyway adding the option to only elaborate the design in vivado in #172 , but if it works locally, we can merge

**Comment by yvantor** [comment]
> Did you try locally? I am anyway adding the option to only elaborate the design in vivado in #172 , but if it works locally, we can merge

It looks like there is a difference in how Synopsys and Vivado like casting a logic variable to enum and vice-versa, so I think the way to solve this is having a define discriminating between ASIC and FPGA implementations

**Comment by yvantor** [comment]
> Did you try locally? I am anyway adding the option to only elaborate the design in vivado in #172 , but if it works locally, we can merge

I did a few fixes, the CI on gitlab is working good!

**Comment by yvantor** [comment]
Closing this.

**Pull request merged**
