### PR TITLE
Bare-metal offloading flow - 1

### PR DESCRIPTION
**Pull request by alex96295**
The table below summarizes the modalities for **offloading a binary to an island in carfield with bare-metal SW** (no GPOS on the RV64 host, no heterogeneous toolchain) for HW verification purposes.

The table assumes the programmer's purpose is to execute a program exclusively on one of carfield's islands different from the host domain (cheshire). It doesn't cover the case where complex interactions between code running on the RV64 host and the other islands are required. Whenever the host RV64 is involved, it's to fulfill the goal of offloading a binary to an island.

More complex SW stack development is currently WIP and will be the flow of reference.

---

| **Offloader** | **Source memory point (host)** | **Source memory point (island binary)** | **Destination memory point (island bynary)** | Host involved? | **Comment** | Status |
| ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| **JTAG** | - | TB virtual memory   | Island private mem. | No | Direct binary preload from outside | ☑ |
| **Serial Link (SL)** | - | TB virtual memory | Island private mem. | No | Direct binary preload from outside | ☑ |
| **Host RV64** | LLC SPM/L2/DRAM | same as host | Shared L2 or island private mem. | Yes | Preload driven by the RV64 host. The host binary encapsulates the island's binary as a header file or directly links the safety island binary in the main host binary. Preloading to the island's destination memory is handled by the host ~or the DMA~. | ☑ |
| ~**JTAG/SL + Host RV64 (mixed)**~ | LLC SPM/L2/DRAM | Shared L2 | Shared L2 or Island private mem. | Yes | Preload driven by SL/JTAG and the RV64 host combined. The SL/JTAG preload the island's binary in the shared L2, and the host or the DMA move the data from L2 to the island's private memory. | □ |

**N.B.** The last one is not addressed in this PR. 

This PR series `Bare metal offloading - X` aim to have a working example with the Safety Island as the test vehicle and be a proxy for other Carfield islands.

### CODE REVIEW

**Comment by alex96295** [comment]
Rebased onto main

**Comment by alex96295** [comment]
Rebased onto main

**Comment by luca-valente** [comment]
@alex96295 is there a typo in the table? I am pretty sure that for the spatz and integer cluster the destination memory should not be the private scratchpad. The pulp_cluster instruction cache is a master on the axi interconnect, connected to the main xbar and to the private L1.

**Comment by alex96295** [comment]
> @alex96295 is there a typo in the table? I am pretty sure that for the spatz and integer cluster the destination memory should not be the private scratchpad. The pulp_cluster instruction cache is a master on the axi interconnect, connected to the main xbar and to the private L1. I think the same applies for spatz?

@luca-valente thanks for pointing that out. For the pulp cluster, yes that is right. For spatz, I think they are directly preloading the private scratchpad memory. @mattsini1 can you comment on this please so that I update the table? Thanks!

**Comment by luca-valente** [comment]
Whenever there is an instruction cache, it is meant to fetch instructions from a distant memory. We should check if spatz has it.

**Comment by alex96295** [comment]
> Whenever there is an instruction cache, it is meant to fetch instructions from a distant memory. We should check if spatz has it.

@mattsini1 is checking :)

**Pull request merged**
