### PR TITLE
Fix integer cluster offloading

### PR DESCRIPTION
**Pull request by yvantor**

### CODE REVIEW

**Comment by alex96295** [comment]
Can we initially merge this one to include the HW modifications in main already, or do you want to wait? I would merge it already (provided the test fix doesn't require HW changes)

**Comment by yvantor** [comment]
> Can we initially merge this one to include the HW modifications in main already, or do you want to wait? I would merge it already (provided the test fix doesn't require HW changes)

Can we wait for a couple of hours more? I also need to push other changes in HW (not related to the broken CI)

**Comment by alex96295** [comment]
> > Can we initially merge this one to include the HW modifications in main already, or do you want to wait? I would merge it already (provided the test fix doesn't require HW changes)
> 
> Can we wait for a couple of hours more? I also need to push other changes in HW (not related to the broken CI)

sure man, just to know ;)

**Comment by yvantor** [comment]
@alex96295 if you want to review this, when the CI concludes we can merge :)

**Review by alex96295 — APPROVED** [review]
LGTM

**Pull request merged**
