### PR TITLE
hw: Set non-zero VGA widths to prevent errors at top level

### PR DESCRIPTION
**Pull request by alex96295**

### CODE REVIEW

**Comment by mp-17** [comment]
LGTM, thanks Ale!

**Review by mp-17 — APPROVED** [review]

**Comment by mp-17** [comment]
@alex96295

**Comment by alex96295** [comment]
> @alex96295

not related to this PR, the ci flow for github also needs an update of the pdk :)

**Comment by alex96295** [comment]
Rebased onto main, it should work now

**Pull request merged**
