### PR TITLE
Hart IDs Alignment.

### LINKED ISSUE #22: Align HARTIDs
Carfield includes several cores, we should align hartids at system level. Current proposal:

```
cva6 -> 0,1
Safey -> 8-10
HMR cluster -> 32-43
Spatz cluster -> 64-...
```

@micprog @yvantor we shall discuss about this

### PR DESCRIPTION
**Pull request by yvantor**
This PR is intended to align the Hart IDs of the available subsystem to the scheme proposed in #22.

Fixes #22

### CODE REVIEW

**Comment by alex96295** [comment]
@yvantor is this PR ready? Are the PRs you opened for the various islands mergeable in their master branches before addressing the merge of this PR?

**Comment by yvantor** [comment]
Let me know if there are any perplexities, otherwise as soon as the CI completes (successfully I hope) we can merge.

**Review by alex96295 — APPROVED** [review]
LGTM

**Comment by yvantor** [comment]
Closing this.

**Pull request merged**
