### PR TITLE
Add pulp-offload-intf.c to stimulate and test CVA6-PULP cluster interference

### PR DESCRIPTION
**Pull request by luca-valente**
I closed #255 and opened this one, rebased on the main branch, and the previous comments addressed.

### CODE REVIEW

**Review by yvantor — APPROVED** [review]
LGTM, waiting on @alex96295  feedback but I think it can be merged.

**Comment by luca-valente** [comment]
@yvantor if only the CI was green :rofl:

**Comment by yvantor** [comment]
These strange CIs ruining all the fun

**Review by alex96295 — APPROVED** [review]
LGTM, grazie :)

**Pull request merged**
