### PR TITLE
Connect AXI user bits for ECC and ATOP

### PR DESCRIPTION
**Pull request by micprog**

### CODE REVIEW

**Comment by alex96295** [comment]
Is this rebased on top of main?

**Comment by micprog** [comment]
> Is this rebased on top of main?

Not yet

**Review by alex96295 — APPROVED** [review]
Apart from a rebase and waiting for #153 , LGTM

**Comment by alex96295** [comment]
I think now the PR could be rebased and squashed, then ready to be merged 
Thanks for the work

**Pull request merged**
